#!/usr/bin/env bash
# configure ufw firewall from all inbcoming traffic
# except 22/ssh 443/https 80/https

apt-get update && apt-get install ufw
sed -i 's/IPV6=.*/IPV6=yes/' /etc/default/ufw
ufw disable
ufw default deny incoming
ufw default allow outgoing
ufw allow 22/tcp
ufw allow 443/tcp
ufw allow 80/tcp
ufw --force enable